# Generated by Django 5.1.4 on 2025-01-08 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
