# Generated by Django 5.1.4 on 2025-01-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Library_app', '0001_initial'),
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Library_app.book'),
        ),
        migrations.AddField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(related_name='admin_channels', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='member_channels', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Library_app.book'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_comments', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Library_app.chapter'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Library_app.channel'),
        ),
        migrations.AddField(
            model_name='repost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='accounts_app.customuser'),
        ),
        migrations.AddField(
            model_name='repost',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='Library_app.channel'),
        ),
        migrations.AddField(
            model_name='repost',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='Library_app.post'),
        ),
    ]
