# Generated by Django 5.1.4 on 2025-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
