# Generated by Django 5.1.4 on 2025-01-10 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0003_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
