# Generated by Django 5.1.4 on 2025-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0005_bookcommentvote_bookvote_chaptervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='rates',
            field=models.IntegerField(default=0),
        ),
    ]
