# Generated by Django 5.1.4 on 2025-01-11 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0006_chapter_rates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_channel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
