# Generated by Django 5.1.4 on 2025-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0007_channel_owner_alter_channel_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
